In [19]:
# # use pandas to read csv file
import pandas as pd 
df = pd.read_csv('./dataset/RegularSeasonCompactResults.csv')

# # print first five row
print(df.head())


# # print last five row
print(df.tail())


# # statistics on the dataframe
print(df.describe())


# # print max value of each column
print(df.max())


# # print Wscore that is greater than 150
print(df[df['Wscore']>150])


# # drop rows and reset index
df=df.drop(index=[2]).reset_index(drop=True)
print(df.head())

# drop column 
df1=df.drop('Season',axis=1)
print('===================')
print(df1)




   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985      20   1228      81   1328      64    N      0
1    1985      25   1106      77   1354      70    H      0
2    1985      25   1112      63   1223      56    H      0
3    1985      25   1165      70   1432      54    H      0
4    1985      25   1192      86   1447      74    H      0
        Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
145284    2016     132   1114      70   1419      50    N      0
145285    2016     132   1163      72   1272      58    N      0
145286    2016     132   1246      82   1401      77    N      1
145287    2016     132   1277      66   1345      62    N      0
145288    2016     132   1386      87   1433      74    N      0
              Season         Daynum          Wteam         Wscore  \
count  145289.000000  145289.000000  145289.000000  145289.000000   
mean     2001.574834      75.223816    1286.720646      76.600321   
std         9.233342      33.287418     104

In [26]:
df=pd.read_csv('./dataset/RegularSeasonCompactResults.csv')
df_new=df[['Season','Daynum']]
print(df_new)

# df_new.to_csv('1234.csv',index=False)

df_daynum=df_new['Daynum'].apply(lambda x : 1 if x>23 else 0)
print(df_daynum)

        Season  Daynum
0         1985      20
1         1985      25
2         1985      25
3         1985      25
4         1985      25
...        ...     ...
145284    2016     132
145285    2016     132
145286    2016     132
145287    2016     132
145288    2016     132

[145289 rows x 2 columns]
0         0
1         1
2         1
3         1
4         1
         ..
145284    1
145285    1
145286    1
145287    1
145288    1
Name: Daynum, Length: 145289, dtype: int64


In [ ]:
url='http://www.stockq.org/'
df=pd.read_html(url)
# print(df[9])
print(df)

In [34]:
import numpy as np 
a = np.array([[1, 2, 3]])
print(a)
print(a.shape)
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)

[[1 2 3]]
(1, 3)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [38]:
df=pd.read_csv('./dataset/demo.csv')

print(df.head())
print(df.shape)
print('===========')
print(type(df['size'].values))

   size  number_room  house_price house_type
0  40.0          3.0          800        old
1  29.0          5.0          700      young
2  33.0          2.0          670      young
3   NaN          2.0          770        old
4   NaN          NaN          870      young
(5, 4)
<class 'numpy.ndarray'>


In [41]:
df=pd.read_csv('./dataset/demo.csv')
print('of nan value in each columns: ')
print(df.isnull().sum())
df_no_missing_=df.dropna()
print(df_no_missing_)
print('fill na with maen')
df['size'].fillna(df['size'].mean(),inplace=True)
print(df)

of nan value in each columns: 
size           2
number_room    1
house_price    0
house_type     0
dtype: int64
   size  number_room  house_price house_type
0  40.0          3.0          800        old
1  29.0          5.0          700      young
2  33.0          2.0          670      young
fill na with maen
   size  number_room  house_price house_type
0  40.0          3.0          800        old
1  29.0          5.0          700      young
2  33.0          2.0          670      young
3  34.0          2.0          770        old
4  34.0          NaN          870      young


In [47]:
import pandas as pd

df=pd.read_csv('./dataset/demo.csv')
print(df)
print('================')
df['house_type']=pd.Categorical(df['house_type']).codes
print(df)
print('============')
df=pd.read_csv('./dataset/demo.csv')
print(df)
dfg=pd.get_dummies(df)
print(dfg)

   size  number_room  house_price house_type
0  40.0          3.0          800        old
1  29.0          5.0          700      young
2  33.0          2.0          670      young
3   NaN          2.0          770        old
4   NaN          NaN          870      young
   size  number_room  house_price  house_type
0  40.0          3.0          800           0
1  29.0          5.0          700           1
2  33.0          2.0          670           1
3   NaN          2.0          770           0
4   NaN          NaN          870           1
   size  number_room  house_price house_type
0  40.0          3.0          800        old
1  29.0          5.0          700      young
2  33.0          2.0          670      young
3   NaN          2.0          770        old
4   NaN          NaN          870      young
   size  number_room  house_price  house_type_old  house_type_young
0  40.0          3.0          800               1                 0
1  29.0          5.0          700               

In [49]:
df = pd.read_csv('./dataset/demo.csv')
nam_array=np.array(df)
print(nam_array)
datafram=pd.DataFrame(nam_array)
print(datafram)

[[40.0 3.0 800 'old']
 [29.0 5.0 700 'young']
 [33.0 2.0 670 'young']
 [nan 2.0 770 'old']
 [nan nan 870 'young']]
      0    1    2      3
0  40.0  3.0  800    old
1  29.0  5.0  700  young
2  33.0  2.0  670  young
3   NaN  2.0  770    old
4   NaN  NaN  870  young


In [64]:
import numpy as np 
from sklearn.model_selection import train_test_split
x=np.arange(20).reshape((10,2))
y=np.arange(10)
print(x,x.shape)
print(y,y.shape)
print('after spliting----------')

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3
)
print(xtrain)
print(xtest)
print(ytrain)
print(ytest)



[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]] (10, 2)
[0 1 2 3 4 5 6 7 8 9] (10,)
after spliting----------
[[ 0  1]
 [18 19]
 [14 15]
 [16 17]
 [ 8  9]
 [10 11]
 [ 2  3]]
[[ 6  7]
 [12 13]
 [ 4  5]]
[0 9 7 8 4 5 1]
[3 6 2]


In [78]:
from sklearn import preprocessing
import numpy as np

x_train = np.array([[ 100., -1.,  2.],
                    [ 900.,  0.,  0.],
                    [ 200.,  1., -1.]])

print(f'mean of x_train: {x_train.mean(axis=0)}')
print(f'std of x_train: {x_train.std(axis=0)}')

# scaler=preprocessing.StandardScaler().fit_transform(x_train)



# print(scaler.mean_)


# x_train=scaler.transform(x_train)
# print(x_train)

x_test=np.array([[-1,1,0]])

# x_test=scaler.transform(x_test)
# print(x_test)


mean of x_train: [4.00000000e+02 0.00000000e+00 3.33333333e-01]
std of x_train: [355.9026084    0.81649658   1.24721913]
[[100.  -1.   2.]
 [900.   0.   0.]
 [200.   1.  -1.]]


In [81]:
from sklearn import preprocessing
import numpy as np

x_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

sc=preprocessing.MinMaxScaler().fit(x_train)
x_train=sc.transform(x_train)
print(x_train)

x_test=np.array([[-3,-1,4]])
x_test=sc.transform(x_test)
print(x_test)

[[0.5        0.         1.        ]
 [1.         0.5        0.33333333]
 [0.         1.         0.        ]]
[[-1.5         0.          1.66666667]]


In [ ]:
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, confusion_matrix
