# Step 1: Create a 3x3 identity matrix called "m1"

In [ ]:
import numpy as np
m1 = np.eye(3)
print(m1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Step 2: Create a vector  called "v1" with values ranging from 0 to 8

In [ ]:
v1 = np.arange(9)
print(v1)

[0 1 2 3 4 5 6 7 8]


# Step 3: Reshape v1 to 3\*3 matrix called m2 

In [ ]:
m2 = v1.reshape(3,3) #np.reshape(v1, (3,3) )
print(m2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Step 4: Calculate element-wise multiply on m1 and m2

In [ ]:
ele_mul = m1 * m2
print(ele_mul)
print("======")
print(np.multiply(m1, m2))

[[0. 0. 0.]
 [0. 4. 0.]
 [0. 0. 8.]]
[[0. 0. 0.]
 [0. 4. 0.]
 [0. 0. 8.]]


# Step 5: Add 3 on each of m1 element (called m3) 

In [ ]:
m3 = m1 + 3
print(m3)

[[4. 3. 3.]
 [3. 4. 3.]
 [3. 3. 4.]]


# Step 6: Calculate m3\*m2 where * is matrix multipy  

In [ ]:
max_mul = np.matmul(m3,m2)
print(max_mul)

[[27. 37. 47.]
 [30. 40. 50.]
 [33. 43. 53.]]


# Step 7: min-max normalization on m3

In [ ]:
# Ref:https://blog.csdn.net/sdu_hao/article/details/104390269

# Min-Max Scaling
normal_m3 = (m3 - m3.min())/(m3.max() - m3.min())
print(normal_m3)

# Z-score Normalization
z_score = (m3-m3.mean())/m3.std()
print(z_score)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 1.41421356 -0.70710678 -0.70710678]
 [-0.70710678  1.41421356 -0.70710678]
 [-0.70710678 -0.70710678  1.41421356]]


# Step 8: sum all of m2 value

In [ ]:
print(np.sum(m2))

36


# Step 9: sum all column vector on m2 matrix

In [ ]:
print(m2)
print("======")
sum_vector = np.sum(m2, axis=0) 
print(sum_vector)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 9 12 15]


# Step 10: Create a random matrix of size 2\*3 and find the mean on each column

In [ ]:
ran_matrix = np.random.random(6).reshape(2,3)
print(ran_matrix)
print("======")
print(np.mean(ran_matrix, axis=0)) #ran_matrix.mean(axis=0) 

[[0.28347954 0.66410323 0.52541628]
 [0.84815661 0.6389366  0.11590823]]
[0.56581808 0.65151992 0.32066225]
